apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: gpu-test-service
  annotations:
    executables.ai.sap.com/name: gpu-test-service
  labels:
    scenarios.ai.sap.com/id: "gpu-test-scenario"
    ai.sap.com/version: "1.0"
spec:
  template:
    apiVersion: serving.kserve.io/v1beta1
    kind: GpuTestService
    metadata:
      name: gpu-test-service
    spec: |
      predictor:
        containers:
          - name: cuopt-container
            image: nvidia/cuopt:latest-cuda12.9-py3.13
            env:
              - name: CUOPT_SERVER_PORT
                value: "8000"
            ports:
              - containerPort: 8000
                protocol: TCP
            resources:
              limits:
                nvidia.com/gpu: 1
              requests:
                cpu: "1"
                memory: "4Gi"
