apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: cuopt-service
  annotations:
    executables.ai.sap.com/name: cuopt-service
  labels:
    scenarios.ai.sap.com/id: "cuopt-scenario"
    ai.sap.com/version: "1.0"
spec:
  template: 
    apiVersion: serving.kserve.io/v1beta1
    kind: InferenceService
    metadata:
      name: cuopt-service
    spec: |
      predictor:
        imagePullSecrets:
          - name: saartha-ai
        containers:
          - name: kserve-container
            image: "docker.io/karthikatsaartha/cuopt-service:0.0.5"
            ports:
              - containerPort: 8000
                protocol: TCP

            env:
              - name: HOME
                value: "/home/appuser"
              - name: TMPDIR
                value: "/tmp"
                
            securityContext:
              readOnlyRootFilesystem: false   # 🔑 CRITICAL FIX
              allowPrivilegeEscalation: false
            volumeMounts:
              - name: writable-tmp
                mountPath: /tmp
              - name: writable-home
                mountPath: /home/appuser
            readinessProbe:
              httpGet:
                path: /health
                port: 8000
              initialDelaySeconds: 60
              periodSeconds: 10
        volumes:
          - name: writable-tmp
            emptyDir: {}
          - name: writable-home
            emptyDir: {}
          

