apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: cuopt-service
  annotations:
    executables.ai.sap.com/name: cuopt-service
  labels:
    scenarios.ai.sap.com/id: "cuopt-scenario"
    ai.sap.com/version: "1.0"
spec:
  template: 
    apiVersion: serving.kserve.io/v1beta1
    kind: InferenceService
    metadata:
      name: cuopt-service
    spec: |
      predictor:
        imagePullSecrets:
          - name: saartha-ai
        containers:
          - name: kserve-container
            image: "docker.io/karthikatsaartha/cuopt-service:0.0.3"
            ports:
              - containerPort: 8000
                protocol: TCP
            env:
              - name: PYTHONDONTWRITEBYTECODE
                value: "1"
              - name: PYTHONUNBUFFERED
                value: "1"
              - name: HOME
                value: "/home/appuser"
              - name: TMPDIR
                value: "/tmp"
            resources:
              limits:
                nvidia.com/gpu: 1
                cpu: "2"
                memory: 8Gi
              requests:
                cpu: "1"
                memory: 4Gi
            readinessProbe:
              httpGet:
                path: /health
                port: 8000
              initialDelaySeconds: 60
              periodSeconds: 10

