apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: cuopt-service
  annotations:
    executables.ai.sap.com/name: cuopt-service
  labels:
    scenarios.ai.sap.com/id: "cuopt-scenario"
    ai.sap.com/version: "1.0"
spec:
  template: 
    apiVersion: serving.kserve.io/v1beta1
    kind: CuoptService
    metadata:
      name: cuopt-service
    spec: |
      predictor:
        imagePullSecrets:
          - name: saartha-ai
        containers:
          - name: kserve-container
            image: "docker.io/karthikatsaartha/cuopt-service:0.0.3"

