apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: image-inference-serving
  labels:
    ai.sap.com/version: "1.0"
spec:
  template:
    apiVersion: serving.kserve.io/v1beta1
    kind: InferenceService
    spec:
      predictor:
        containers:
          - name: kserve-container
            image: docker.io/karthikatsaartha/image-inference:1.0
            ports:
              - containerPort: 8000
