apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: image-inference-serving
  annotations:
    executables.ai.sap.com/name: image-inference
  labels:
    scenarios.ai.sap.com/id: "inference-scenario"
    ai.sap.com/version: "1.0"
spec:
  template: 
    apiVersion: serving.kserve.io/v1beta1
    kind: InferenceService
    metadata:
      name: image-inference
    spec: |
      predictor:
        imagePullSecrets:
          - name: saartha-ai
        containers:
          - name: kserve-container
            image: "docker.io/karthikatsaartha/image-inference:1.7"
            command:
              - /bin/sh
              - -c
            args:
              - uvicorn app.main:app --host 0.0.0.0 --port 8080
            ports:
              - containerPort: 8080
                protocol: TCP
