apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: image-inference-serving
  annotations:
    executables.ai.sap.com/name: image-inference
  labels:
    ai.sap.com/version: "1.0"
spec:
  template: 
    apiVersion: serving.kserve.io/v1beta1
    kind: InferenceService
    metadata:
      name: image-inference
    spec: |
      predictor:
        containers:
          - name: kserve-container
            image: "docker.io/karthikatsaartha/image-inference:1.0"
            command:
              - /bin/sh
              - -c
            args:
              - uvicorn main:app --host 0.0.0.0 --port 8000
            ports:
              - containerPort: 8000
