apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: image-inference-serving
  annotations:
    scenarios.ai.sap.com/id: "inference-scenario"
    executables.ai.sap.com/name: "image-inference"
  labels:
    scenarios.ai.sap.com/id: "inference-scenario"
    ai.sap.com/version: "2.0"
spec:
  inputs:
    parameters:
      - name: resourcePlan
        type: string
        default: "starter"
      - name: postgresHost
        type: string
        default: "10.20.1.158"
      - name: postgresPort
        type: string
        default: "5432"
      - name: postgresUsername
        type: string
        default: "postgres"
      - name: postgresPassword
        type: string
        default: "root"
      - name: postgresDbname
        type: string
        default: "ai_data_store"
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      name: "{{.workflow.name}}"
      labels:
        ai.sap.com/resourcePlan: "{{.inputs.parameters.resourcePlan}}"
    spec: |
      predictor:
        imagePullSecrets:
          - name: saartha-ai
        minReplicas: 1
        maxReplicas: 2
        containers:
        - name: kserve-container
          image: docker.io/karthikatsaartha/gopro_postgres:0.0.2
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: POSTGRES_HOST
            value: "{{.inputs.parameters.postgresHost}}"
          - name: POSTGRES_PORT
            value: "{{.inputs.parameters.postgresPort}}"
          - name: POSTGRES_USERNAME
            value: "{{.inputs.parameters.postgresUsername}}"
          - name: POSTGRES_PASSWORD
            value: "{{.inputs.parameters.postgresPassword}}"
          - name: POSTGRES_DBNAME
            value: "{{.inputs.parameters.postgresDbname}}"
