apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: image-inference-serving
  annotations:
    executables.ai.sap.com/name: image-inference
spec:
  template:
    metadata:
      labels:
        ai.sap.com/resource.parent: image-inference
    spec: |
      name: image-inference
      image: index.docker.io/mydockeruser/image-inference:latest
      models:
        - name: imagenet
          path: /models
      replicas: 1
      ports:
        - name: http
          port: 8080
